In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [15]:
data = pd.read_csv('./Data/grad_demo_fin_abs.csv')

In [16]:
data

,grad_rate,ECONOMICALLY_DISADVANTAGED,H_Female,AA_FEMALE,W_FEMALE,AA_MALE,W_MALE,H_MALE,AA,H,W,Expend_per_pupil,CHRONIC_ABSENT
0,0.96,0.247442,0.008372,0.002791,0.465116,0.007442,0.500465,0.001860,0.010233,0.010233,0.965581,9171.37,0.151
1,0.95,0.339286,0.010714,0.020536,0.409821,0.019643,0.505357,0.016071,0.040179,0.026786,0.915179,9523.76,0.178
2,0.92,0.199858,0.044097,0.070413,0.351351,0.085349,0.346373,0.046942,0.155761,0.091038,0.697724,12546.31,0.175
3,0.98,0.193347,0.037422,0.016632,0.382536,0.027027,0.482328,0.037422,0.043659,0.074844,0.864865,9106.97,0.171
4,0.89,0.371846,0.169323,0.086321,0.228420,0.083001,0.255644,0.160691,0.169323,0.330013,0.484064,7418.07,0.169
...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,0.94,0.247493,0.058575,0.078100,0.335620,0.079683,0.362005,0.063852,0.157784,0.122427,0.697625,7842.51,0.216
262,0.97,0.071171,0.018018,0.044595,0.407207,0.050450,0.420270,0.024775,0.095045,0.042793,0.827477,7519.21,0.126
263,0.96,0.185639,0.005254,0.021016,0.432574,0.035026,0.476357,0.021016,0.056042,0.026270,0.908932,10360.40,0.149
264,0.97,0.109044,0.027390,0.050646,0.375711,0.047028,0.430491,0.033592,0.097674,0.060982,0.806202,7995.72,0.150
265,0.94,0.120000,0.026667,0.013333,0.600000,0.013333,0.293333,0.013333,0.026667,0.040000,0.893333,20049.13,0.096

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   grad_rate                   266 non-null    float64
 1   ECONOMICALLY_DISADVANTAGED  266 non-null    float64
 2   H_Female                    266 non-null    float64
 3   AA_FEMALE                   266 non-null    float64
 4   W_FEMALE                    266 non-null    float64
 5   AA_MALE                     266 non-null    float64
 6   W_MALE                      266 non-null    float64
 7   H_MALE                      266 non-null    float64
 8   AA                          266 non-null    float64
 9   H                           266 non-null    float64
 10  W                           266 non-null    float64
 11  Expend_per_pupil            266 non-null    float64
 12  CHRONIC_ABSENT              266 non-null    float64
dtypes: float64(13)
memory usage: 27.1 KB

In [18]:
X = data.drop(columns='grad_rate')
y = data.grad_rate

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25)

In [20]:
scaler = StandardScaler()

In [21]:
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns)
X_test = pd.DataFrame(scaler.transform(X_test), columns = X_test.columns)

In [22]:
X_train.to_csv('./Data/X_train_scaled.csv', index=False)
X_test.to_csv('./Data/X_test_scaled.csv', index=False)

In [23]:
y_train.to_csv('./Data/y_train.csv')
y_test.to_csv('./Data/y_test.csv')

In [27]:
X_train

,ECONOMICALLY_DISADVANTAGED,H_Female,AA_FEMALE,W_FEMALE,AA_MALE,W_MALE,H_MALE,AA,H,W,Expend_per_pupil,CHRONIC_ABSENT
0,-0.153815,-0.466203,-0.710654,0.802172,-0.643418,0.790054,-0.704797,-0.680552,-0.599158,0.806615,-0.931578,0.559400
1,0.720830,-0.288571,1.669558,-1.436411,1.765628,-1.364820,-0.328516,1.724815,-0.312981,-1.418607,-0.711182,0.079856
2,-1.106824,0.023436,-0.671118,0.416609,-0.667036,0.782712,-0.082533,-0.672155,-0.033260,0.611191,0.877505,-0.754134
3,-0.043676,-0.406650,-0.388962,0.527286,-0.378064,0.251891,-0.472331,-0.385332,-0.446094,0.392128,0.550149,-0.118217
4,-0.286501,-0.960367,-0.673081,0.856576,-0.690300,0.923356,-0.852168,-0.684691,-0.912044,0.902481,-0.939594,-0.962631
...,...,...,...,...,...,...,...,...,...,...,...,...
194,-0.656727,-0.025173,-0.702650,0.700759,-0.680828,0.595536,-0.180491,-0.695033,-0.108880,0.655778,-0.268298,-0.952206
195,-0.215338,-0.404521,-0.626437,0.929074,-0.584521,0.488097,-0.529504,-0.608508,-0.475805,0.713783,-0.816129,0.455151
196,0.186532,-0.653148,0.330821,-0.680144,-0.340977,0.650138,0.055430,-0.000825,-0.279113,-0.002369,4.145573,4.374902
197,1.817720,-0.284676,2.411833,-2.026980,2.457977,-1.986017,-0.481721,2.445717,-0.393454,-2.032867,0.222602,3.999607
198,-0.741905,0.722529,0.760066,-0.005848,-0.018540,-1.192055,-0.112581,0.377410,0.281219,-0.618385,5.105331,0.163255