In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('./Data/grad_demo_fin_abs.csv')

In [3]:
data

,grad_rate,ECONOMICALLY_DISADVANTAGED,H_Female,AA_FEMALE,W_FEMALE,AA_MALE,W_MALE,H_MALE,AA,H,W,Expend_per_pupil,CHRONIC_ABSENT
0,0.96,0.247442,0.008372,0.002791,0.465116,0.007442,0.500465,0.001860,0.010233,0.010233,0.965581,9171.37,0.151
1,0.95,0.339286,0.010714,0.020536,0.409821,0.019643,0.505357,0.016071,0.040179,0.026786,0.915179,9523.76,0.178
2,0.92,0.199858,0.044097,0.070413,0.351351,0.085349,0.346373,0.046942,0.155761,0.091038,0.697724,12546.31,0.175
3,0.98,0.193347,0.037422,0.016632,0.382536,0.027027,0.482328,0.037422,0.043659,0.074844,0.864865,9106.97,0.171
4,0.89,0.371846,0.169323,0.086321,0.228420,0.083001,0.255644,0.160691,0.169323,0.330013,0.484064,7418.07,0.169
...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,0.94,0.247493,0.058575,0.078100,0.335620,0.079683,0.362005,0.063852,0.157784,0.122427,0.697625,7842.51,0.216
262,0.97,0.071171,0.018018,0.044595,0.407207,0.050450,0.420270,0.024775,0.095045,0.042793,0.827477,7519.21,0.126
263,0.96,0.185639,0.005254,0.021016,0.432574,0.035026,0.476357,0.021016,0.056042,0.026270,0.908932,10360.40,0.149
264,0.97,0.109044,0.027390,0.050646,0.375711,0.047028,0.430491,0.033592,0.097674,0.060982,0.806202,7995.72,0.150
265,0.94,0.120000,0.026667,0.013333,0.600000,0.013333,0.293333,0.013333,0.026667,0.040000,0.893333,20049.13,0.096

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   grad_rate                   266 non-null    float64
 1   ECONOMICALLY_DISADVANTAGED  266 non-null    float64
 2   H_Female                    266 non-null    float64
 3   AA_FEMALE                   266 non-null    float64
 4   W_FEMALE                    266 non-null    float64
 5   AA_MALE                     266 non-null    float64
 6   W_MALE                      266 non-null    float64
 7   H_MALE                      266 non-null    float64
 8   AA                          266 non-null    float64
 9   H                           266 non-null    float64
 10  W                           266 non-null    float64
 11  Expend_per_pupil            266 non-null    float64
 12  CHRONIC_ABSENT              266 non-null    float64
dtypes: float64(13)
memory usage: 27.1 KB

In [5]:
X = data.drop(columns='grad_rate')
y = data.grad_rate

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25)

In [7]:
scaler = StandardScaler()

In [8]:
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns)
X_test = pd.DataFrame(scaler.transform(X_test), columns = X_test.columns)

In [9]:
X_train.to_csv('./Data/X_train_scaled.csv', index=False)
X_test.to_csv('./Data/X_test_scaled.csv', index=False)

In [10]:
y_train.to_csv('./Data/y_train.csv',index=False)
y_test.to_csv('./Data/y_test.csv', index=False)

In [11]:
X_train

,ECONOMICALLY_DISADVANTAGED,H_Female,AA_FEMALE,W_FEMALE,AA_MALE,W_MALE,H_MALE,AA,H,W,Expend_per_pupil,CHRONIC_ABSENT
0,0.696901,0.801826,0.331287,-0.372913,0.235424,-0.550370,1.033731,0.285619,0.931789,-0.471111,-0.559159,-0.359952
1,-1.142674,-0.522320,-0.582366,0.719782,-0.508044,0.536584,-0.498137,-0.548634,-0.514418,0.637110,-0.871599,-1.191341
2,-0.149305,-0.755786,-0.589409,0.711704,-0.583934,0.738387,-0.720162,-0.589735,-0.744018,0.737569,0.092061,0.471437
3,-0.149904,-0.597624,-0.565079,0.863452,-0.618058,0.526724,-0.464774,-0.594166,-0.533029,0.703718,-0.301450,-0.823004
4,0.368851,-0.231378,1.766711,-1.523159,2.002200,-1.601720,-0.002872,1.892167,-0.112845,-1.589623,1.240014,0.061004
...,...,...,...,...,...,...,...,...,...,...,...,...
194,0.952769,-0.911503,-0.757663,0.858149,-0.713655,0.965430,-0.720281,-0.739812,-0.819004,0.928226,-0.419652,2.186834
195,0.665253,-0.813629,-0.734616,0.867825,-0.772882,1.016041,-0.770161,-0.757304,-0.798258,0.959261,0.446035,-0.665145
196,1.116337,3.097391,1.704282,-2.117622,1.539256,-2.208951,2.883975,1.631497,3.013553,-2.200762,-2.034465,1.439636
197,-0.011506,1.700566,-0.467166,-0.010246,-0.518670,-0.113447,2.266782,-0.495020,2.015483,-0.063855,-0.603785,-0.549382
198,2.896157,-0.655276,2.739169,-2.289120,2.995690,-2.330720,-0.438374,2.880020,-0.546825,-2.349414,1.766660,3.533894